- name: Import STACK playbook
  import_playbook: ans_stack.yml
  vars:
    stack_dir: "../net-stack"
    mgmt_name: wan0
    stack_name: labv10
    tag_name: labs
    stack_update: false
    stack_template: "st_lab_bgpv3.yaml"
  when: not stack_skip|bool

- name: HUAWEI=>> Import HUAWEI playbook
  import_playbook: ans_huawei.yml

- name: HUAWEI=>> Import CISCO playbook
  import_playbook: ans_cisco.yml
