---
- name: Configure Cisco IOS
  hosts: cisco
#  connection: local
  vars:
    ospf_check: False
    do_it: True
    int_reset: True

  roles:
#     - { role: interfaces, when: interfaces is defined }
#     - router-config
#     - { role: ospf, when: ospf is defined }
# # #    - dmvpn
#     - { role: eigrp, when: eigrp is defined }
#     - { role: redistribute, when: redistribute is defined }

    - { role: interfaces }
    - { role: router-config }
    - { role: ospf }
# # #    - dmvpn
    - { role: eigrp }
    - { role: bgp }
    - { role: redistribute }
  
  tasks:
    - name: Write config to router
      ios_command:
        commands: "wr mem"
      tags:
        - never
