- name: STACK=>>Create stack {{ stack_name }}
  hosts: localhost
  gather_facts: false

  tasks:
    - name: STACK=>>Display name template
      debug:
        msg: "{{ stack_template }}"
    
    - name: STACK=>>Check if exist stack {{ stack_name }}
      openstack.cloud.stack_info:
        name: "{{stack_name}}"
      register: stack
      failed_when: (stack.stacks|length > 0) and (not stack_update|bool)

    - name: STACK=>>create stack
      #ignore_errors: True
      register: stack_create
      openstack.cloud.stack:
        name: "{{ stack_name }}"
        tag: "{{ tag_name }}"
        state: present
        template: "{{stack_dir}}/{{stack_template}}"
        # parameters:
        #     wan_ip: "{{ wan_ip }}"

    # - name: STACK=>> Show stack - {{stack_create}}
    #   debug:
    #     msg: "{{ stack_create }}"
    #   when: not stack_skip|bool

- name: "STACK=>>Refresh inventory file"
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - meta: refresh_inventory

- name: STACK=>>Wait for port 22 to be ready
  hosts: all
  gather_facts: False
  tasks:

    - name: Wait 300 seconds for port 22 to become open
      wait_for:
        port: 22
        host: "{{ ansible_ssh_host }}"
        delay: 10

