- name: PREPARE=>>Check variables and files
  hosts: localhost
  gather_facts: false
  vars:
    stack_dir: "../net-stack"
    mgmt_name: wan0
  
  tasks:
    - name: PREPARE=>>Check if variable 'stack_name' exist 
      debug:
        msg: "{{ stack_name }}"
      failed_when: stack_name|length == 0

    - name: PREPARE=>>Check if variable 'stack_template' exist 
      debug:
        msg: "{{ stack_template }}"
      failed_when: stack_name|length == 0

    - name: PREPARE=>>Creating a file oslabs.yml for dynamic inventory
      copy:
        dest: "./oslabs.yml"
        content: |
          ---
          wan: {{ mgmt_name }}
          lab: {{ stack_name }}
      delegate_to: localhost

- name: Import STACK playbook
  import_playbook: ans_stack.yml
  vars:
    stack_dir: "../net-stack"
    stack_update: false
    tag_name: labs
  when: not stack_skip|bool

- name: HUAWEI=>> Import HUAWEI playbook
  import_playbook: ans_huawei.yml

- name: HUAWEI=>> Import CISCO playbook
  import_playbook: ans_cisco.yml
